### ISSUE TITLE
Compliance Exception : Cert

### ISSUE THREAD

**Issue by avrossi** [WhenLamboMoon/docker-zen-node#25]
Im getting a Compliance Exceptions : CERT? My node says cert valide: true. But I'm getting that compliance exception. Is this normal? Thanks

**Comment by avrossi** [comment]
And my challenges are all passing no problem.

**Comment by 333miiko** [comment]
Did you get your compliance exception before or after your challenge passed? 

Perhaps your DNS provider is having an issue? I'm not too sure what else could be the cause, especially if your challenges are passing and cert valid is returning true. 

How long was the exception for? If it was interim I would write it off as an zen tracking issue since I'm aware they've been having a few issues. Hopefully they resolve this soon.

Let me know if it happens again.

**Comment by avrossi** [comment]
I got the compliance exception before the challenges passed.
The exception was only for 1 sec. so I assume it was just a blip.
I sent you a Zencash donation yesterday.  Thanks for all  your help!

**Comment by 333miiko** [comment]
Thanks!

Yep if it was just 1 second it's most likely just a blip, they've had a few with bal and peer blips too. Feel free to re-open this issue if it happens again but I have a feeling they'll iron out these issues soon.
